name: 🐛 Bug Report
description: Report a reproducible bug or regression
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide as much detail as possible.
  - type: input
    id: pytorch-version
    attributes:
      label: PyTorch version
      placeholder: "e.g. 2.9.0"
  - type: input
    id: cuda-version
    attributes:
      label: CUDA version
      placeholder: "e.g. 12.8"
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Install torch.whl
        2. Run python script
        3. Observe error
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      render: shell
