name: Test Install PyTorch Wheel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install-test:
    runs-on: ubuntu-latest

    container:
      image: nvidia/cuda:12.8.0-runtime-ubuntu22.04
      options: --gpus all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apt update
          apt install -y wget curl python3-pip

      - name: Set up Python 3.10 manually  # ✅ 容器中未自动安装
        run: |
          apt install -y software-properties-common
          add-apt-repository ppa:deadsnakes/ppa -y
          apt update
          apt install -y python3.10 python3.10-venv python3.10-dev python3.10-distutils
          update-alternatives --install /usr/bin/python python /usr/bin/python3.10 1
          curl -sS https://bootstrap.pypa.io/get-pip.py | python

      - name: Download wheel from latest GitHub release
        id: download
        run: |
          mkdir -p dist
          RELEASE_URL=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest \
            | grep browser_download_url \
            | grep '.whl"' \
            | cut -d '"' -f 4)

          if [ -z "$RELEASE_URL" ]; then
            echo "No release found. Skipping wheel test."
            exit 0
          fi

          WHEEL_NAME=$(basename "$RELEASE_URL")
          wget "$RELEASE_URL" -O "dist/$WHEEL_NAME" || {
            echo "Failed to download wheel: $RELEASE_URL"
            exit 1
          }
          echo "WHEEL_NAME=$WHEEL_NAME" >> $GITHUB_OUTPUT

      - name: Install from wheel
        if: steps.download.outputs.WHEEL_NAME
        run: |
          chmod +x install_from_whl.sh
          ./install_from_whl.sh "dist/${{ steps.download.outputs.WHEEL_NAME }}"

      - name: Verify installation
        if: steps.download.outputs.WHEEL_NAME
        run: |
          python examples/demo_tensor_cuda.py

      - name: Final check
        if: always()
        run: |
          echo "✅ Test complete! Believe in light, your PyTorch wheel is ready to shine!"
