name: Test Install PyTorch Wheel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y wget

      - name: Download wheel from latest GitHub release
        id: download
        run: |
          mkdir -p dist
          RELEASE_URL=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest \
            | grep browser_download_url \
            | grep '.whl"' \
            | cut -d '"' -f 4)

          if [ -z "$RELEASE_URL" ]; then
            echo "No release found. Skipping wheel test."
            exit 0
          fi

          WHEEL_NAME=$(basename "$RELEASE_URL")
          wget "$RELEASE_URL" -O "dist/$WHEEL_NAME" || {
            echo "Failed to download wheel: $RELEASE_URL"
            exit 1
          }
          echo "WHEEL_NAME=$WHEEL_NAME" >> $GITHUB_OUTPUT

      - name: Install from wheel
        if: steps.download.outputs.WHEEL_NAME
        run: |
          set -x
          chmod +x install_from_whl.sh
          ./install_from_whl.sh "dist/${{ steps.download.outputs.WHEEL_NAME }}"

      - name: Verify installation
        if: steps.download.outputs.WHEEL_NAME
        run: |
          set -x
          python examples/demo_tensor_cuda.py

      - name: Final check
        if: always()
        run: |
          echo "Test complete! Believe in light, your PyTorch wheel is ready to shine!"
          if [ $? -ne 0 ]; then
            echo "Some steps failed. Check logs for details."
          fi
